# Generated by Django 4.1.2 on 2022-11-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paymets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymets',
            name='order',
        ),
        migrations.AddField(
            model_name='paymets',
            name='order',
            field=models.ManyToManyField(to='api.order'),
        ),
    ]
