# Generated by Django 4.1.2 on 2022-11-25 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_paymets_order_paymets_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymets',
            name='order',
        ),
        migrations.AddField(
            model_name='paymets',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
    ]
