# Generated by Django 4.1.2 on 2022-11-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_paymets_order_paymets_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymets',
            name='payment_satus',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
